project_id = "xymsmdfodoovnrkqhqyv"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
recover_session_from_url = false
external_email_enabled = true
external_phone_enabled = true
sms_provider = "twilio"
sms_max_frequency = 5
sms_otp_exp = 60
sms_otp_length = 6
email_max_frequency = 5
email_otp_exp = 60
email_otp_length = 6
external_anonymous_users_enabled = false
external_google_enabled = false
external_apple_enabled = false
external_azure_enabled = false
external_bitbucket_enabled = false
external_discord_enabled = false
external_facebook_enabled = false
external_figma_enabled = false
external_github_enabled = false
external_gitlab_enabled = false
external_keycloak_enabled = false
external_linkedin_oidc_enabled = false
external_notion_enabled = false
external_slack_oidc_enabled = false
external_spotify_enabled = false
external_twitch_enabled = false
external_twitter_enabled = false
external_workos_enabled = false
external_zoom_enabled = false
external_fly_enabled = false
password_min_length = 6
password_strength = "low"
enable_signup = true
enable_anonymous_signups = false

[db]
port = 54322

[functions]
verify_jwt = false

[functions.transcribe-video]
verify_jwt = false

[functions.extract-insights]
verify_jwt = false

[functions.trim-video]
verify_jwt = false

[realtime]
enabled = true
port = 54323
ip_version = "ipv4"

[storage]
enabled = true
port = 54324
image_transformation_enabled = true

[edge_runtime]
policy = "per_request"
inspector_port = 8083

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"